name: PR Review
on: 
  pull_request_review:
    types: [submitted]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Label approved PRs
      if: github.event.review.state == 'approved'
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['Approved']
          })

    - name: Label PRs with requested changes
      if: github.event.review.state == 'changes_requested'
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['Changes Requested']
          })
